apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartprod-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartprod-front
  template:
    metadata:
      labels:
        app: smartprod-front
    spec:
      containers:
        - name: front
          image: seuusuario/smartprod-front:latest
          ports:
            - containerPort: 5173
