apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartprod-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartprod-front
  template:
    metadata:
      labels:
        app: smartprod-front
    spec:
      containers:
        - name: smartprod-front
          image: smartprod-front:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://smartprod-api-service:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: smartprod-front-service
spec:
  type: NodePort
  selector:
    app: smartprod-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
